### ISSUE TITLE
AttributeError in PlantCV

### ISSUE THREAD

**Issue by RavinduDharmasena** [danforthcenter/plantcv#367] opened 2019-04-25 09:23 UTC
### Description
I am a newbie to plantCV. I tried to run the PlantCV NIR pipeline tutorial in Visual Studio Code in my Windows. machine Unfortunately I am getting the following error.

Traceback (most recent call last):
  File "testNIR.py", line 134, in <module>
    main()
  File "testNIR.py", line 40, in main
    bkg_sub_thres_img = pcv.threshold.custom_range(bkg_sub_img, [50], [190], 'gray')
AttributeError: module 'plantcv.plantcv.threshold' has no attribute 'custom_range'

### Changes I made
I just changed the line 
   img_bkgrd = cv2.imread("background_nir_z2500.png", flags=0)
to
   img_bkgrd = cv2.imread(args.image, flags=0)

to accept image as a command line argument.

Secondly added a 'b' to the beginning of following line
    kg_sub_thres_img = pcv.threshold.custom_range(bkg_sub_img, [50], [190], 'gray')

### Another question, but not a issue
Additionally, I have a small question which is not a issue. How can I read the NIR intensities of pixels of a NIR image using plantCV. I need to do that for my research project. Is there any python libraries for that if I can't do it using plantCV.

**Comment by nfahlgren** [comment] 2019-04-25 12:03
Hi @RavinduDharmasena, thanks for reaching out, we are happy to help you get set up. PlantCV will be able to extract the NIR intensities from your object of interest in the image once we get it working.

The error you are getting sounds like it is not importing PlantCV correctly. It looks like it might be the same issue that happened in #363. 

The two quick things to check are first make sure you are doing `from plantcv import plantcv as pcv` rather than `import plantcv as pcv`. The second is like #363, make sure that the `plantcv` folder is not in the working directory of Visual Studio. When you ask Python to import a package it will look in the local directory first which will cause PlantCV to be imported incorrectly. The quick fix is to either rename the plantcv folder or move it to another location.

If neither of those things are the issue, could you provide how you installed PlantCV?

Thanks!

**Comment by RavinduDharmasena** [comment] 2019-04-25 12:47
There isn't any folder on my working directory of visual studio code. I followed the conda installation instructions on PlantCV documentation (url:https://plantcv.readthedocs.io/en/latest/installation) to install the plantCV module because I'm trying to use it in Django framework. I installed it to a separate conda environment to practice the plantCV.  To execute the python script I used following command.

python testNIR.py -i C:\Users\acer\Documents\Test_NIR\MG_8764_RGB-grayscale.jpg -o /home/user/output-images -D

As the image I used an grayscale image(MG_8764_RGB-grayscale.jpg) generated from an NIR drone image. I didn't uploaded it because it is larger than 10MB.
I omitted the 'print' part because in windows it will generates an runtime error as follows

usage: testNIR.py [-h] -i IMAGE [-m ROI] [-o OUTDIR] [-D]
testNIR.py: error: unrecognized arguments: 'print'


Here is the python script that I'm trying to execute on visual studio code. (contains only the python script. I have to zip it to upload it to GitHub because GitHub doesn't support .py files).
[testNIR.zip](https://github.com/danforthcenter/plantcv/files/3116875/testNIR.zip)

**Comment by HaleySchuhl** [comment] 2019-04-25 13:17
Hello @RavinduDharmasena ,

The function `pcv.threshold.custom_range` was merged into master after our most recent release and since we haven't yet done a v3.3 release, that function isn't in the conda environment just yet! 😅
 If you replace `kg_sub_thres_img = pcv.threshold.custom_range(bkg_sub_img, [50], [190], 'gray')`
with `bkg_sub_thres_img = cv2.inRange(bkg_sub_img, 50, 190)` this ought to get rid of the attribute error. Otherwise you would need to clone master to have the most up to date version of PlantCV. We will be releasing v3.3 soon though!

Also, thank you for pointing out the typo with the missing 'b'. I'll be sure to correct that. Let us know if this corrects the error, and definitely don't hesitate if you find anything else!

**Comment by RavinduDharmasena** [comment] 2019-04-25 17:06
I installed plantCV again using github repo. When I executed the command

python testNIR.py -i C:\Users\acer\Documents\Test_NIR\MG_8764_RGB-grayscale.jpg -o /home/user/output-images -D

in that repository after copying the testNIR.py file to repository it says image is not grayscale even though the image is grayscale version of NIR drone image. Error that appear in the console is given below.

$ python testNIR.py -i C:\Users\acer\Documents\Test_NIR\MG_8764_RGB-grayscale.jpg -o /home/user/output-images -D
Traceback (most recent call last):
  File "testNIR.py", line 134, in <module>
    main()
  File "testNIR.py", line 37, in main
    bkg_sub_img = pcv.image_subtract(img, img_bkgrd)
  File "C:\Users\acer\Documents\Test_NIR\plantcv\plantcv\plantcv\image_subtract.py", line 32, in image_subtract
    fatal_error("Input image is not gray-scale")
  File "C:\Users\acer\Documents\Test_NIR\plantcv\plantcv\plantcv\fatal_error.py", line 14, in fatal_error
    raise RuntimeError(error)
RuntimeError: Input image is not gray-scale
(plantcv)

I tried to execute same python script that given above.

**Comment by HaleySchuhl** [comment] 2019-04-25 18:37
Hi @RavinduDharmasena , from looking at the python script you included above I'm unable to reproduce your error. When using `cv.imRead` the `flags=0` ensures that images are read in as grayscale (many times images that look grayscale will still have 3 channels so this flag is important to include). The default flag loads a color image and will cause `pcv.image_subtract` to fail. The function expects `len(np.shape(img)) == 2` and `len(np.shape(img_bkgrd)) == 2`. 

I did notice that the change from `img_bkgrd = cv2.imread("background_nir_z2500.png", flags=0)` to `img_bkgrd = cv2.imread(args.image, flags=0)` will make it such that `img_bkgd` is the exact same as your original image. If you do not have a background image I would suggest skipping the background subtraction all together and adjust the workflow accordingly. Optionally, you could replace line 34 `img_bkgrd = cv2.imread("background_nir_z2500.png", flags=0)` with `img_bkgrd = np.zeros(np.shape(img)[:2], dtype=np.uint8)` so you can subtract a pure black image with the same dimensions as your original image to avoid changing the workflow.

**Comment by RavinduDharmasena** [comment] 2019-04-26 06:20
I tried to do what you said, but it ended in a failure by throwing this error

Traceback (most recent call last):
  File "testNIR.py", line 134, in <module>
    main()
  File "testNIR.py", line 77, in main
    comb_img = pcv.logical_or(e1_img, bkg_sub_thres_img)
  File "C:\Users\acer\Documents\Test_NIR\plantcv\plantcv\plantcv\logical_or.py", line 26, in logical_or
    merged = cv2.bitwise_or(bin_img1, bin_img2)
TypeError: src2 is not a numerical tuple

The command I executed is 
python testNIR.py -i C:\Users\acer\Documents\Test_NIR\MG_8764_RGB-grayscale.jpg -o C:\Users\acer\Documents\Test_NIR\output -D

I tried to do this on the downloaded plantCV github repo.

As an amateur, I don't know is there something wrong with the images that I used for the tutorial. So I decided to upload the 2 image files that I tried to use with this tutorials. I need to read the NIR intensity of a NIR image using plantCV.  

ZIP file given below conatins following files.
   testNIR.py - python script that I tried to execute in downloaded plantCV GitHub repo
   sr-sunshots-grayscale-p1.jpg - grayscale image that I downloaded from the internet
   IMG_8764_RGB.jpg - NIR drone image

[Test_NIR.zip](https://github.com/danforthcenter/plantcv/files/3119893/Test_NIR.zip)

Due to the large file size of the grayscale version of NIR drone image (14 MB), I uploaded it to my google drive and using this link you can download it.
https://drive.google.com/file/d/1Ov0tddtTlv14zuAV8WiCnmmv8me15ceJ/view?usp=sharing

**Comment by HaleySchuhl** [comment] 2019-04-26 16:10
@RavinduDharmasena It looks like this error is coming from OpenCV (`pcv.logical_or` is a wrapper of `cv2.logical_or`). I expect that it is throwing that error because the version of OpenCV isn't compatible with PlantCV, but looking at your drone image I think that the NIR Tutorial isn't well suited for your purposes. Many of the steps in the tutorial aim at object segmentation (we want to analyze only plant pixels so we segment out background). The tutorial was written specifically to work on the example images and is meant to show people how to combine the modular functions in PlantCV. Are you interested in segmenting out any parts of the drone image before collecting NIR intensities? 

If you'd like to collect NIR intensities for the entire image I would suggest the following workflow:
```
#!/usr/bin/python
import os
import sys, traceback
import cv2
import numpy as np
import argparse
import string
from plantcv import plantcv as pcv

def options():
    parser = argparse.ArgumentParser(description="Imaging processing with opencv")
    parser.add_argument("-r","--result", help="result file.", required= False )
    parser.add_argument("-i", "--image", help="Input image file.", required=True)
    parser.add_argument("-m", "--roi", help="Input region of interest file.", required=False)
    parser.add_argument("-o", "--outdir", help="Output directory for image files.", required=False)
    parser.add_argument("-D", "--debug", help="Turn on debug, prints intermediate images.", action="store_true")
    args = parser.parse_args()
    return args

### Main pipeline
def main():
    # Get options
    args = options()
    
    pcv.params.debug=args.debug #set debug mode
    pcv.params.debug_outdir=args.outdir #set output directory
    
    # Read image 
    img, path, img_name = pcv.readimage(args.image, mode='native')
    
    # Split RGB channels
    b, g, r = cv2.split(img)
    
    # Create a white mask the same size as the image
    mask = np.ones(np.shape(img)[:2], np.uint8)

    # Perform signal analysis
    pcv.analyze_nir_intensity(gray_img=r, mask=mask, bins=256, histplot=False)
        
    # Write NIR data to results file
    pcv.print_results(filename=args.result)


# Call program
if __name__ == '__main__':
    main()
``` 
The drone image appears to have stored NIR pixel values in the red channel which is why I use the red channel to do NIR intensity analysis on. 

The command I executed is
`python testNIR.py -i ./IMG_8764_RGB.jpg -o ./output -D -r ./output/nir_data.txt` 

Let me know if this works for your purposes!

**Comment by RavinduDharmasena** [comment] 2019-04-27 03:58
It is working perfectly fine. Thank you so much for your effort. It might really useful in my research part in future. But is there a way to get just the NIR intensities of each pixel as an array ?.

**Suggestion**
Can you add tutorials for retrieving NIR values from an image as an array and for this histogram one ?

This are the only use cases that I can think so far. But I must tell there are lots of use cases in the plantCV.
So more tutorials for plantCV in documentation will ensure more use case coverage of plantCV

**Comment by nfahlgren** [comment] 2019-04-27 19:18
Hi @RavinduDharmasena, images in PlantCV (and most Python packages that handle images) are stored as NumPy [ndarrays](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html). In NIR (grayscale) images this is a 2-dimensional array where the NIR intensities are the values of each cell in the array. If you want to linearize an ndarray, they have a built-in method called `flatten`. In the context of the code @HaleySchuhl sent you you can add in this to the script:

```python
nir_array = a.flatten()
```

**Comment by RavinduDharmasena** [comment] 2019-04-28 06:03
I understand what you said and still I'm looking at it. But as a amateur in python and plantCV, still I wasn't able to connect the ndarrays to the script and I never know such a thing before. How to use flatten() method in script and if I need to write it to a file, is there a library like fs in NodeJS ?.

**Comment by nfahlgren** [comment] 2019-04-28 23:27
Sorry, I said `a.flatten()` but it should have been `nir_array = r.flatten()`. 

I am not sure what you want to do with the pixel values afterwards but there are several different ways to write the data out to a file. If you want to save the data to a text file, since `nir_array` is a NumPy array you could use [np.savetxt](https://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html).

**Comment by HaleySchuhl** [comment] 2019-05-30 15:10
Feel free to reopen with any other questions/suggestions!

**Closed by HaleySchuhl** 2019-05-30 15:10 UTC

**Comment by RavinduDharmasena** [comment] 2019-06-01 09:03
Sure. Sorry for my inactivity for a long time.
