### ISSUE TITLE
Thermal tutorial error + error in reading in and plotting thermal csv data

### ISSUE THREAD

**Issue by spurdom** [danforthcenter/plantcv#611] opened 2020-08-26 19:17 UTC
This is my first attempt to use Plant CV to process thermal images of soybeans grown in small plots. What I would like to be able to do is read the images in, threshold/edge detection to remove soil pixels and then calculate average canopy temperature. Keep in mind - I'm very new to python, thanks for any and all help!

**Issue 1:** I've been attempting to read one of my images into my Jupyter Notebook following the workflow/tutorial in the documentation. Here is the code I have been trying and the resulting error. I have been successful in reading the image in as a jpg just using matplotlib. 

<img width="542" alt="cell 1" src="https://user-images.githubusercontent.com/70239477/91345927-c0e3dc00-e7a5-11ea-9aa0-dbae105d5e9e.png">
<img width="566" alt="cell 2" src="https://user-images.githubusercontent.com/70239477/91345941-c6412680-e7a5-11ea-8d1a-7d8465360441.png">
<img width="564" alt="cell 3" src="https://user-images.githubusercontent.com/70239477/91345956-c9d4ad80-e7a5-11ea-99da-32637c5fecf4.png">

**Issue 2:** I was attempting to use the Plant CV thermal interactive tutorial and running the first cell is giving me an error message:

<img width="842" alt="cell 1_2" src="https://user-images.githubusercontent.com/70239477/91346368-5a12f280-e7a6-11ea-96df-fc5f093e87dd.png">

**Local environment:**
 - OS: Windows 10
 - Jupyter Notebook
 - PlantCV Version 3.9.0

**Comment by nfahlgren** [comment] 2020-08-26 19:28
Hi @spurdom! For issue 1, the code in the documentation is taken from a Python script, so modification is needed to plug the same code into a Jupyter notebook. Your first cell is good. In the second cell you can remove the `def options` block of code and replace it with:

```
# Handle input variables
# This code was provided to make it easier to convert the notebook to a script
class options():
    def __init__(self):
        self.debug = "plot"
        self.result = "0001_IR.txt"
        self.outdir = "./output_images"
        self.writeimg = False
        self.image = "0001_IR.csv"
```

Then in the following cells, remove the `def main():` code and remove the code indentation. Typically you will want to run one plantcv command per subsequent cell to visualize the output.

But all that being said, here is a link to the Jupyter notebook for the thermal tutorial: https://github.com/danforthcenter/plantcv-binder/blob/master/notebooks/thermal.ipynb so you can see an example.

For issue 2 it looks like there is something broken with the interactive tutorial system, we're looking into it now.

**Comment by nfahlgren** [comment] 2020-08-26 19:56
@spurdom, the Binder links are working again. Thanks for pointing out the issue!

**Comment by spurdom** [comment] 2020-08-26 21:55
@nfahlgren, Thanks for help, I have it working now. One more question that came up when I finished the processing was the conversion of the JSON .txt to csv format.

I've tried the command line code in the documentation:
plantcv-utils.py json2csv [-h] -j JSON -c CSV

Am I right in assuming you just add the filenames to that line, for example:
plantcv-utils.py json2csv [-h] -j imagename.txt -c imagename

I've tried this, but also not working, or at least I can't find where it's saving the files. I can see my .txt output from the image processing in my Jupyter Notebook dashboard but not the converted csv. 

Thanks again, and sorry for the beginner questions.

**Comment by nfahlgren** [comment] 2020-08-26 22:33
No problem @spurdom, great questions! A confusing aspect of our output JSON files is that there are really two different kinds. When you run an individual workflow (Jupyter or as a script) and save a results file you get the type of JSON file you have. We should make this clearer but we treat this as an intermediate file. When you run `plantcv-workflow.py` to analyze a dataset with your workflow it collects these JSON files and merges them into one final output JSON file. Currently, `plantcv-utils.py json2csv` will only convert the final merged version, not the intermediate versions. 

We should fix this because I can understand why someone would want to be able to work with individual outputs from a workflow. Or someone could run their workflows with another tool rather than `plantcv-workflow.py`. 

To bypass the issue quickly, there is a trick you can do to convert your JSON file into one of the type that the json2csv converter can use.

On the command-line you can run the below where `./test` is a directory with your 1+ JSON files in it, and `imgname.json` is the output file you want. Note that it tries to append to `imgname.json`, so you may need to delete that first unless you are trying to append to it.

```bash
python -c 'import plantcv.parallel;plantcv.parallel.process_results("./test", "imgname.json")'
```

Once you have the output `imgname.json` file, then you can run `plantcv-utils.py json2csv -j imgname.json -c imgname

Alternatively, you could do it all in Jupyter without the command-line:

```python
import plantcv.parallel
import plantcv.utils
plantcv.parallel.process_results(job_dir="./test", json_file="imgname.json")
plantcv.utils.json2csv(json_file="imgname.json", csv_file="imgname")
```

**Comment by spurdom** [comment] 2020-08-27 18:09
Ok @nfahlgren, that last code you sent me for Jupyter worked to create two csv files - one called single value traits and one called multi value traits, but they are empty and I think that's because I actually never had a JSON file for this single image output - I'm assuming that this function will come into play when I am running a whole set of images. Maybe my last question was the wrong one. My **next** step will be trying to translate this workflow into running a whole set of images, but for now I'm just trying to get the hang of the system - for this step I just want to convert this output text file from my thermal analysis into a formatted csv that can be read into excel or R. 

[0001_IR.txt](https://github.com/danforthcenter/plantcv/files/5138032/0001_IR.txt):

Thanks again for help with the rookie questions.

**Comment by nfahlgren** [comment] 2020-08-27 20:20
Hi @spurdom, for sure, totally makes sense. The JSON file you attached as a result of your workflow run on a single image has results in it, so that's good! It has both single-value results (e.g. max_temp, min_temp, mean_temp, and median_temp) as well asl multi-value results (e.g. thermal_frequencies - a histogram of temperatures).

So I think the issue is likely just something with the last block of code above. For `plantcv.parallel.process_results` to work correctly the file input as `args.result` needs to be saved into a directory (this has to do with how the parallel stuff works). Changing the top of your workflow with something like this might do the trick:

```python
import os
# Handle input variables
# This code was provided to make it easier to convert the notebook to a script
class options():
    def __init__(self):
        self.tmp_dir = "./json_files"
        self.debug = "plot"
        self.result = os.path.join(self.tmp_dir, "0001_IR.txt")
        self.outdir = "./output_images"
        self.writeimg = False
        self.image = "0001_IR.csv"
        os.makedirs(self.tmp_dir, exist_ok=True)
```

Then a modification to the last part of the code:

```python
import plantcv.parallel
import plantcv.utils
plantcv.parallel.process_results(job_dir=args.tmp_dir, json_file="imgname.json")
plantcv.utils.json2csv(json_file="imgname.json", csv_file="imgname")
```

**Comment by spurdom** [comment] 2020-09-02 15:02
@nfahlgren , I still haven't been successful converting the output .txt file from analysis into a usable format, however, now a new issue came up overnight. As you can see in the following image, I'm getting an error when I try to run the "analyze_thermal_values" function and my ouput file is now empty except for two headings. 

![image](https://user-images.githubusercontent.com/70239477/92000612-5251d180-ed03-11ea-889b-5a5c6b559b1c.png)

Seems like I need to fix this problem before I can work on the output format. Do you have any suggestions? Thanks again, and I would appreciate any suggestions of resources to improve my literacy in jupyter notebooks.

**Comment by nfahlgren** [comment] 2020-09-02 16:27
Hi @spurdom, I think it looks like you have things in Jupyter working well, the error may be some sort of data type issue or bug potentially. Would you mind sharing an example file from your thermal dataset so I can do some testing? If so, feel free to drop it into the issue here, or if you would rather email it you can send it to nfahlgren@danforthcenter.org. Thanks!

**Comment by spurdom** [comment] 2020-09-02 20:05
Here is an example csv thermal image file; this is the file that I have been working with in Jupyter to try to get the workflow functioning. I conveted it to .xlsx because I couldn't upload a csv here:

[0001_IR.xlsx](https://github.com/danforthcenter/plantcv/files/5164564/0001_IR.xlsx)

and here is what it looks like in jpg:
![0001_IR](https://user-images.githubusercontent.com/70239477/92030928-5d215c00-ed2d-11ea-97c8-10bcaf796057.jpg)


Thanks a lot.
Sam

**Comment by nfahlgren** [comment] 2020-09-02 20:41
Thanks Sam!

I had a few mistakes in the code I suggested above but was able to put together a small workflow that works (I opened the Excel file and saved as CSV). It does not use a mask that looks at any subregion of the image, it just keeps the whole thing in the analysis.

[thermal_workflow.ipynb.zip](https://github.com/danforthcenter/plantcv/files/5164722/thermal_workflow.ipynb.zip)

**Comment by spurdom** [comment] 2020-09-03 21:44
@nfahlgren, Thanks for putting that together. Unfortunately I'm still getting an error from the "analyze thermal values" step of the process and I think that's preventing me from creating results as well:

<img width="717" alt="error 9-3" src="https://user-images.githubusercontent.com/70239477/92176696-a2648d00-ee04-11ea-8e84-d937f0d81a2d.png">

**Comment by nfahlgren** [comment] 2020-09-04 01:49
There's not a known issue I am aware of but your version of OpenCV is a bit out of date with what we're using (3.4.2 vs 3.4.9). It would be worth updating your environment to rule that out as an issue.

**Closed** 2021-06-10 15:46 UTC
Labels: help wanted
