### ISSUE TITLE
Test whether masked background pixel values can be nan

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#310] opened 2019-01-24 20:45 UTC
### Description

See #306:

> Would it be an issue for any masking functions/lines to replace masked pixels with np.nan instead of 0? this would make colormaps more intuitive, e.g. with using the hsv colormap.

### Completion Criteria

Test whether masked pixels can be set to `nan`.

**Comment by HaleySchuhl** [comment] 2019-01-24 21:42
Hi @dschneiderch! 

So far it seems like you can definitely replace masked pixels with `np.nan`. I've tried it in the PSII interactive tutorial example. The line used to read 
`fvfm_header, fvfm_data, fvfm_images = pcv.fluor_fvfm(fdark,fmin,fmax,kept_mask, args.outdir+'/'+filename, 1000)`

and I successfully ran the following instead: 
`retval, new_mask=cv2.threshold(kept_mask, 100, np.nan, cv2.THRESH_TOZERO)`
`fvfm_header, fvfm_data, fvfm_images = pcv.fluor_fvfm(fdark,fmin,fmax,new_mask, args.outdir+'/'+filename, 1000)`

This same thresholding worked with `pcv.median_blur` but need to try out more functions that taken binary images as input. For the time being you can definitely use this thresholding with your mask used in `pcv.fluor_fvfm`.

**Comment by HaleySchuhl** [comment] 2019-01-30 15:23
@dschneiderch I totally agree! I realizes that using `cv2.THRESH_TOZERO` was having no effect on the image. In the `pcv.pseudocolor` function we now mask pixels to np.nan if a mask is provided. The function gives users more control (select any matplotlib colormap, optionally mask out background in the pseudocolored image, optionally provide min & max_values for pseudocoloring).

Feel free to reopen if anything comes up!

**Comment by dschneiderch** [comment] 2019-01-30 16:47
I noticed another small issue that could be addressed in this new function. My pseudocolor images are being printed flipped horizontally compared to the original grey scale image.
![image](https://user-images.githubusercontent.com/7461221/51997342-63719700-246b-11e9-87b7-a19efe4df8e0.png)
If you print `cv2.flip(fvfm,1)` it works out.

Lastly, it would be clever if you could cropped the image to the extents (+ a small buffer) of the roi so you don't get the big space between the colorbar and the plant. stretch goal :-)

**Comment by HaleySchuhl** [comment] 2019-02-04 18:43
Hello @dschneiderch,

I haven't been able to recreate this image flipping. When I read in the grayscale images and use the fluor_fvfm function, the output matches the orientation of the images I read in. Also, the pseudocolor function would break if we flip the grayscale image without flipping the optional mask. Let me know if you have any updates of how your images are getting flipped.  

I do plan to add an autocrop with buffer feature to the function (likely next week). Within this update we will likely add an optional dpi argument as well!

**Comment by dschneiderch** [comment] 2019-02-05 18:14
Hi @HaleySchuhl  
Sorry for the trouble. I can't reproduce this on my computer with any variation of fluor_fvfm.py either so we can close for now.
If it happens again I will investigate more thoroughly.

**Closed by dschneiderch** 2019-02-05 18:14 UTC
Labels: enhancement
