### ISSUE TITLE
PlantCV & OpenCV 3?

### ISSUE THREAD

**Issue by macluca** [danforthcenter/plantcv#130] opened 2017-03-29 23:12 UTC
I'm looking to try out PlantCV. I saw the 2.0 update is available. Is it compatible with OpenCV3.X yet, or is it just 2?

**Comment by nfahlgren** [comment] 2017-03-30 01:39
@macluca, still OpenCV2. OpenCV3 is on our roadmap for PlantCV3, which we will start working on as soon as we finalize the v2 release. It's the top feature on the list for v3, but it would be available as soon as it's ready, even if the official v3 release takes awhile to finalize.

**Comment by jshoyer** [comment] 2017-03-30 15:39
For the record, this issue is effectively a duplicate of #21.

Is the roadmap distinct from the set of GitHub milestones? Is it a private document?

I am confused by the title of the corresponding [milestone #1](https://github.com/danforthcenter/plantcv/milestone/1). Does "Update PlantCV dependencies to OpenCV3/Python3" mean that future versions of plantCV will _not_ be compatible with Python 2 and/or OpenCV 2?


@macluca: Are there specific features present in OpenCV 3 (but not 2) that you would find useful?

**Comment by nfahlgren** [comment] 2017-03-30 16:21
@jshoyer the only official "roadmap" is the GitHub milestones. They could be improved, and/or the new GitHub Projects functionality might be a better way to organize goals. There are two older milestones that are specific to an EPSCoR project we had, versus the newer milestone for PlantCV3 would encompass the updates to OpenCV3 and Python3 as well as other v3 features.

I'm not sure about backwards compatibility at this point, mostly because I don't know how many changes we will need to incorporate OpenCV3 (I know some of the functions have different inputs than in v2). Or more importantly, is there functionality that fundamentally changes that won't allow us to be flexible? I think (for now) cross-compatibility with Python2 and 3 will be possible, at least until one of our dependencies stops supporting Python2.

**Closed** 2017-07-12 16:54 UTC
