### ISSUE TITLE
ImporError Installing

### ISSUE THREAD

**Issue by MjBordalo** [danforthcenter/plantcv#134] opened 2017-04-02 19:05 UTC
Hello guys, 
trying to install PlantCV  but  got this error, i already tried to install using:

python setup.py install --prefix /home/miguel/plantCV_top

from branch master and dev.
Got this error:

Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

Thanks in advace

**Comment by nfahlgren** [comment] 2017-04-02 22:53
Hi @MjBordalo,

`setuptools` is a Python package that is used by the `setup.py` script to do the installation. If you have `pip` available on your system you can install setuptools in your home directory with `pip install --user setuptools`. If you do not have `pip`, you can install a user copy following the instructions [here](https://pip.pypa.io/en/stable/installing/). Installing `pip` will automatically install setuptools.

Alternatively, you can append the plantcv directory to your PYTHONPATH to bypass installation. For the bash shell you would add `export PYTHONPATH=$PYTHONPATH:/home/miguel/plantcv` (or wherever you cloned plantcv to) to the file `~/.bash_profile`.

Hope that helps!

**Comment by MjBordalo** [comment] 2017-04-02 23:19
Hi @nfahlgren  thanks 4 the help.

It helped but know i have another problem:
/usr/local/lib/python2.7/dist-packages/setuptools/dist.py:334: UserWarning: Normalizing '2.0-dev' to '2.0.dev0'
  normalized_version,
running install
Checking .pth file support in /home/miguel/plantCV_top/lib/python2.7/site-packages/
/usr/bin/python -E -c pass
```
TEST FAILED: /home/miguel/plantCV_top/lib/python2.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH
```

i also checked the file ''' .bash_profile''' in order to bypass installation but its not there..

`miguel@miguel-Lu:~$  less .bash
.bash_history  .bash_logout   .bashrc       `

**Comment by nfahlgren** [comment] 2017-04-02 23:25
I think the `.pth` file error is that the path you are installing into is not in your PYTHONPATH (if I remember correctly).

You can modify your PYTHONPATH in `~/.bashrc` instead of `~/.bash_profile`.

**Comment by MjBordalo** [comment] 2017-04-02 23:33
Okay i added the export line you suggested to `~/.bashrc` file and then moved to plantcv folder and runed:
```
miguel@miguel-Lu:~/plantcv$ python -c 'import plantcv'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "plantcv/__init__.py", line 27, in <module>
    from watershed import watershed_segmentation
  File "plantcv/watershed.py", line 7, in <module>
    from scipy import ndimage as ndi
ImportError: No module named scipy
```

**Comment by nfahlgren** [comment] 2017-04-02 23:39
Looks like it's finding the package, so now the external package dependencies need to be installed. Here's the list of our dependencies that can be installed with `pip`:

```
pip install --user argparse
pip install --user matplotlib
pip install --user numpy
pip install --user pandas
pip install --user pytest
pip install --user python-dateutil
pip install --user scikit-image
pip install --user scipy
```

The other dependency is OpenCV, which cannot be installed with `pip`, do you know if you have that installed?

**Comment by MjBordalo** [comment] 2017-04-02 23:42
okay why is this getting so difficult to me?
I  am following the Linux Ubuntu instructions.. (i am on lubuntu tought)
So i only runed:
`sudo apt-get install git libopencv-dev python-opencv sqlite3`

**Comment by nfahlgren** [comment] 2017-04-02 23:46
Gotcha, that is correct. The other Python packages are installed automatically by setuptools, but if you do not use the setup script they have to be installed manually. So if we back up, it looks like setuptools might not be installed by default on Ubuntu like I thought. I will need to add that to the apt-get command.

**Comment by nfahlgren** [comment] 2017-04-02 23:47
`sudo apt-get install python-setuptools` will install the Ubuntu package.

**Comment by MjBordalo** [comment] 2017-04-02 23:53
not sure if i am following..
Anyway did that successfully but camming back to installation i was not able to do it..

**Comment by nfahlgren** [comment] 2017-04-02 23:59
The error about `fatal error: Python.h: No such file or directory` can probably be fixed by installing the Python development headers: `sudo apt-get install python-dev`.

I will need to test on lubuntu to clean up the installation docs. Maybe the issue is that I tested Ubuntu server edition and your lubuntu is a desktop edition? The server addition might have some of these tools installed by default, which I didn't realize.

**Comment by MjBordalo** [comment] 2017-04-03 00:00
At this time let me ask you the following:
I am installing plantCV because i wanted to use it for part of my thesis. i want to evaluate the weight of my hydroponics plants using a camera with a top view of them.
Do u think plantCV is the best way to go for me?

Thanks (sorry for deviating the subject for a secound)

**Comment by nfahlgren** [comment] 2017-04-03 00:02
No worries. I think PlantCV can do that. Would your pictures looks something like the ones in this tutorial? http://plantcv.readthedocs.io/en/latest/multi-plant_tutorial/

**Comment by MjBordalo** [comment] 2017-04-03 00:05
Yes exactly that tutorial gave me a lot of the motivation so far :P.
So actually i am only using lubuntu because i wanted to try it in my virtualmaxine before going to the pi .
i can try in the pi if that helps..
( i dont think your last suggestion helped either, i am afraid my linux skills are lacking now..)

**Comment by nfahlgren** [comment] 2017-04-03 00:18
Hmm, you could try this `sudo apt-get install python-matplotlib` to install matplotlib using the Ubuntu package manager.

**Comment by MjBordalo** [comment] 2017-04-03 00:19
Okay actually it did help, i installed it in the PlantCV folder and did the pip installations and i am sucessfully running the test file

**Comment by MjBordalo** [comment] 2017-04-03 00:19
tomorrow ill play with it :)
Thanks 4 the help!

**Comment by nfahlgren** [comment] 2017-04-03 00:20
Great, thanks!

**Comment by MjBordalo** [comment] 2017-04-03 00:20
ill it run with no worries in raspberry pi?

**Comment by nfahlgren** [comment] 2017-04-03 00:23
I have run it before on a Pi with Raspbian Wheezy (I do not think I have tested Jessie). Installing OpenCV on a Pi was tricky if I recall correctly, but it was doable.

**Comment by MjBordalo** [comment] 2017-04-03 11:40
oh shit.. next battle

**Closed** 2017-04-03 11:40 UTC
