### ISSUE TITLE
JSONDecodeError using outputs.save_results

### ISSUE THREAD

**Issue by jksshack** [danforthcenter/plantcv#1645] opened 2024-12-19 18:46 UTC
**Bug:**
I was running a modified version of the multiplant tutorial in jupyterlab.  Earlier today the outputs.save_results function worked well, however after some playing around with rois I'm getting JSONDecodeError.  I went back and ran a copy I had saved yesterday (when there was no error), it **also**? now is throwing the same error.  Any idea what's going on and how I could remedy this?  

** Code**
`%matplotlib widget`
`from plantcv import plantcv as pcv `
`from plantcv.parallel import WorkflowInputs`
`args = WorkflowInputs(
    images=["./img/rasppi.png"],    
    names="image1",
    result="piresults.json",
    outdir=".",
    writeimg=True,
    debug="plot",
    sample_label="genotype"
    )
`
`pcv.params.debug = args.debug`
`img, path, filename = pcv.readimage(filename=args.image1)`
`gaussian_img = pcv.gaussian_blur(img=img, ksize=(11, 11), sigma_x=0, sigma_y=None)`
`a = pcv.rgb2gray_lab(rgb_img=gaussian_img, channel='b')`
`a_thresh = pcv.threshold.binary(gray_img=a, threshold=145)
`
`a_fill = pcv.fill(bin_img=a_thresh, size=500)`
`a_fill=pcv.fill_holes(a_fill)`
`roi1 = pcv.roi.rectangle(img=img, x=1200, y=0, h=img.shape[0], w=2200)`
`kept_mask = pcv.roi.filter(mask=a_fill, roi=roi1, roi_type='partial')
`
`labeled_mask, num_plants = pcv.create_labels(mask=kept_mask)`
`shape_img = pcv.analyze.size(img=img, labeled_mask=labeled_mask, n_labels=num_plants)`
line throwing the error
`pcv.outputs.save_results(filename=args.result, outformat="json")`

**Image being processed:**
[image.zip](https://github.com/user-attachments/files/18201730/image.zip)

**Error Message**
![errormessage](https://github.com/user-attachments/assets/6a221827-ae09-482a-87d3-cb511306985b)

When I go to open the json there is also this message
![Screenshot 2024-12-19 144800](https://github.com/user-attachments/assets/b101f4a9-1526-4f3c-8af2-bca39c37cb79)

**Local environment**
 - OS: Windows
 - Environment conda: plantcv
 - PlantCV Version - unknown?  Downloaded a month ago

**Comment by HaleySchuhl** [comment] 2024-12-19 19:50
Hi @jksshack thanks for opening this issue. I think the problem is that the function is trying to append your observations from the current workflow into the existing outfile. This behavior is in place for parallelization, but when running in jupyter on a single image the formatting is a little different. 

Can you write the updated observations to a brand new results file?

**Comment by jksshack** [comment] 2024-12-19 20:16
That worked, love a simple fix!  Thank you so much!!

**Comment by HaleySchuhl** [comment] 2024-12-19 21:57
Awesome! Happy to help. Closing this issue for now but feel welcome to reopen with further questions or suggestions.

**Closed by HaleySchuhl** 2024-12-19 21:57 UTC
Labels: help wanted
