### ISSUE TITLE
Calibrated Image generation

### ISSUE THREAD

**Issue by parthphoenix** [danforthcenter/plantcv#574] opened 2020-05-18 09:53 UTC
Hi @DannieSheng @HaleySchuhl,

I'm working on a project where relative reflectance needs to be considered in Hyperspectral Image processing. I have explored PlantCV but can't able to find it. Without it, I'm not getting reflectance value between 0 to approx(1). 
Is there any way to consider dark reference and white reference to calculate relative reflectance with PlantCV?
I have npy datacube and metadata files to generate R.
R = I - D / W - D
where I = raw data file(.npy)
          D = Dark reference
          W = White reference
Any help will be appreciated.

**Comment by HaleySchuhl** [comment] 2020-05-18 13:08
Hello @parthphoenix ,

Thanks for reaching out about hyperspectral image reflectance calibration! We do have a calibration tool built into the PlantCV hyperspectral sub-package that takes white and dark reference and  raw image data to create a calibrated image. Unfortunately, based on your description I'm not sure if the tool is something you can use right now since the workflow for using PlantCV to calibrate expects that you read in image data `pcv.readimage` but if I remember correctly your metadata file is a different format than the `.hdr` files we currently support. We want to extend the functionality though so hopefully we can add support for your specific files output by your hyperspec camera.

For right now, here is the raw code to our calibration tool so you can extend the calibration algorithm to work on .npy files. I would prefer to work together on extending PlantCV to read in your image data so that you can just use our tools as intended! We just need a sample image and metadata file to start working on adjusting `pcv.readimage` to handle your data :) Let me know what you think!

**Comment by parthphoenix** [comment] 2020-05-18 14:32
Hi @HaleySchuhl 
I want to correct your information. I have metadata(.hdr) file and .npy datacube. let me know the preferred way you want the sample data.

**Comment by HaleySchuhl** [comment] 2020-05-18 14:39
@parthphoenix thanks! Sending a zipped folder with both should be easiest.

**Comment by parthphoenix** [comment] 2020-05-18 14:58
@HaleySchuhl  Here's the link of shared data. 
https://drive.google.com/open?id=1oSKgLQVlM8wA4JSq1nVq1OCPsFJvbQBM

FYI, I have tested PlantCV workflow and the results are available in the folder itself.
You probably see the reflectance graph, where you find the reflectance graph is not normalized between 0 to 1. It's not calibrated. It should be calibrated.

**Comment by HaleySchuhl** [comment] 2020-05-20 12:04
Hi @parthphoenix ,

I got a chance to look at the data you shared yesterday. I'm not sure how you're reading in the .npy file into PlantCV but I tried to read in your white and dark reference images and found that your .hdr files share a similar issue with another collaborator (see issue #565 for more detail). I updated the function and opened a pull request. We can probably get those updates merged into master sometime today. 

With these updates you should be able to read both reference images in as intended and then use [`pcv.hyperspectral.calibrate`](https://plantcv.readthedocs.io/en/latest/calibrate/) the same way it is used in the example on the doc page.

**Comment by nfahlgren** [comment] 2020-05-20 20:41
Just an update that the changes @HaleySchuhl mentioned above were merged into PlantCV this afternoon

**Comment by parthphoenix** [comment] 2020-05-26 04:17
Thanks, @HaleySchuhl @nfahlgren 
Apologies, Last week I was too busy with other work.

@HaleySchuhl, FYI, I've made several changes in **read_data.py** to make .npy file compatible.

I will check the changes you've made. Thanks again.

**Closed** 2020-06-03 09:46 UTC
