### ISSUE TITLE
plantcv on jetson nano

### ISSUE THREAD

**Issue by noman-bashir** [danforthcenter/plantcv#570] opened 2020-04-17 01:54 UTC
Hi all, 

Has anyone successfully installed plantcv on jetson nano? I have tried every installation method given in the documentation. 

- Conda does not work on ARM
- docker container gives "exec format error"
- script-based installation always ends with a new error. Every time a new package is missing matplotlib, plotline,  etc. 

I would highly appreciate guidance on this. 

Thanks in advance.

**Comment by nfahlgren** [comment] 2020-04-17 03:31
Hi @noman-bashir!

I haven’t tried on a jetson nano but have installed on a Raspberry Pi from time to time. I recall looking at it again recently and I think the issue is that there’s no ARM-based OpenCV package, at least as far as I saw in conda and PyPI. OpenCV could be compiled from source though and I believe the rest of the PlantCV package would install correctly.

It would be great if we could work out the procedure and add it to the installation docs.  I don’t think I have a Pi with me for testing at the moment but happy to help figure it out.

**Comment by noman-bashir** [comment] 2020-04-17 20:15
Hi @nfahlgren!

Thanks for the response. I was able to install the OpenCV using instructions given on [Install Opencv 4.1 on Nvidia Jetson Nano](https://pysource.com/2019/08/26/install-opencv-4-1-on-nvidia-jetson-nano/.) 

After that, I tried script-based installation that ended with the following error 

`ImportError: No module named _internal.cli.main`


An online solution suggested upgrading the pip, which I did using "`python -m pip install --upgrade pip`". 

I tried "bash scripts/setup.sh" again, it says already installed. I next tried "from plantcv import plantcv" in both python 2.7 and python 3.6. In python 2.7, it gives the following error:

`SyntexError: Non-ASCII character '\xc3' in file plantcv/plantcv/hyperspectral/extract_index.py on line 398, but no encoding declared.`

On python 3.6, it gives the following error:

`ModuleNotFoundError: No module named 'plotline'`

I have not been able to resolve any of the issues yet, any suggestions are welcomed. I will update if I figure it out.

**Comment by dschneiderch** [comment] 2020-04-17 20:31
at the very least looks like a typo  `plotnine` instead of `plotline`

**Comment by nfahlgren** [comment] 2020-04-17 21:34
Hi @noman-bashir, it looks like we have not kept the script-based installation method up to date, it's creating a Python 2.7 virtualenv but we stopped supporting Python 2 late last year. So we definitely need to fix that.

In Python 3.6 you installed via `pip`?

**Comment by noman-bashir** [comment] 2020-04-18 12:47
I was testing both python versions inside the "plantcv" directory and getting the aforementioned errors. I was doing this because the installation script said the following.

```
cd /home/username/plantcv
source /home/username/plantcv/venv/bin/activate/
python
```

If I go to any other directory, even after activating the virtual environment, I get the `ImportError: No module named plantcv`. 

Are there any suggestions on how can I fix the SyntexError and ImportError outside the plantcv directory? It would be nice if it works for Python3 as well. 

Note: I installated OpenCV for python 3 as well.

**Comment by nfahlgren** [comment] 2020-04-20 01:48
The virtual environment is not going to work with the script-based installation method because the procedure is broken/out of date, so for now we need to use a different installation procedure.

After you clone the PlantCV GitHub repository, edit the `requirements.txt` file and remove `opencv-python<4, >=3.4`.

Install the dependencies using `pip` (make sure it's the pip that is tied to your Python 3 installation, not Python 2).

```bash
pip3 install -r requirements.txt
```

Then install PlantCV:

```bash
python3 setup.py install
```

Note that when you then try to import plantcv you need to be outside the clone of the GitHub repo and it cannot be in your working directory. This is because Python will see a folder called "plantcv" and will think you are trying to import from the directory rather than the package.

**Comment by noman-bashir** [comment] 2020-04-20 15:59
Thanks for the suggestion. I have been trying the same thing for the last 2 days. Scipy is causing is problems as of now. Scikit-image requires statsmodel which requires scipy version >=1.0. Apt-get install 0.19 version of scipy and pip is not able to install scipy at all, probably due to architecture incompatibility.

**Comment by nfahlgren** [comment] 2020-04-20 16:30
Possibly scipy needs to be compiled from source? https://raspberrypi.stackexchange.com/questions/8308/how-to-install-latest-scipy-version-on-raspberry-pi

**Comment by noman-bashir** [comment] 2020-04-20 20:16
Yes, I was going through the same link. There were a lot of version issues, but I am happy to share that it is installed, I am able to run `from plantcv import plantcv`. Thank you for all the help.

**Comment by nfahlgren** [comment] 2020-04-20 20:18
Awesome! Would you be willing to provide the overall protocol you used? We could add a section to the installation guide (with credit to you).

**Comment by noman-bashir** [comment] 2020-04-20 20:51
Sure. I will write it down, test on another image, and get back.

**Comment by nfahlgren** [comment] 2020-10-06 16:43
Closing for now but feel free to reopen!

**Closed by nfahlgren** 2020-10-06 16:43 UTC
Labels: documentation, enhancement
